runner:
  phpmd:
    cmd: phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  phpstan:
    cmd: phpstan analyse -c phpstan.neon.dist --error-format=raw --no-progress
    format: phpstan
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --output-format=text --config=psalm.xml --no-progress --use-baseline=psalm-baseline.xml
    format: psalm
    name: psalm
    level: warning