runner:
  phpmd:
    cmd: phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  phpstan:
    cmd: phpstan analyse -c phpstan.neon.dist --error-format=checkstyle --no-progress
    format: checkstyle
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --no-progress --output-format=checkstyle
    format: checkstyle
    name: psalm
    level: warning